### ISSUE TITLE
Feature Request: Random effect in univariable models

### ISSUE THREAD

**Issue by epi-stats** [ewenharrison/finalfit#104]
Thanks again for the great package. I use it a lot.

There is one thing that could be improved.
Currently a random effect is only used in the multivariable model, not in the univariable models.
However, a random effect is usually required by the study design (at least in my area of research).
So an argument for using lme4 in all models would be great.

I have played around a bit, but the code below does not really work very well.

<code>
glmuni <- function (.data, dependent, explanatory, random_effect = NULL, family = "binomial", ...) 
{
    result <- list()
    if(is.null(random_effect)){
      for (i in 1:length(explanatory)) {
        result[[i]] <- ff_eval(glm(ff_formula(dependent, explanatory[i]), 
            data = .data, family = family, weights = !!sym(weights), 
            ...))
        result[[i]]$call$formula <- formula(result[[i]])
      }
    }
    else{
      random_effect = paste0("(1 | ", random_effect, ")")
      for (i in 1:length(explanatory)) {
          result[[i]] <- lme4::glmer(paste0(dependent, "~", explanatory[i], " + ", random_effect), 
                                       data = .data, family = "binomial", 
                                       control = lme4::glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e+05))) 
      }
   } 
    class(result) = "glmlist"
    return(result)
}    

finalfit <- function ...
...
    glmuni.out = do.call(glmuni, c(list(.data = .data, dependent = dependent, 
        explanatory = explanatory,  random_effect = random_effect), model_args_in))
...
</code>
    
All the best
Jan

**Comment by ewenharrison** [comment]
Thanks for your interest, it is greatly appreciated. 
It is an important point. 
The work around is here, and relatively straightforward I hope. 

https://finalfit.org/articles/all_tables_examples.html#b-mixed-effects-random-intercept-model-with-univariable-estimates-including-random-effects

Please let me know what you think. 
Ewen

**Comment by ewenharrison** [comment]
Thanks Jan. 
Variables do not need to be factors. 
`rack` and `nutrient` as you say only have two unique values, so they are inappropriately labelled as an `integer`. 
The standard `finalfit()` function will convert any continuous variables to a factor if it has only a few unique values, controlled with the `cont_cut` argument. 
There are two options then. Convert them to the factors that they probably are. 
Or pass `cont_cut = 1` to `finalfit()` if you wish to consider them as integers/numerics. 

e.g.. 
```
> library(finalfit) 
> library(lme4)
> 
> data(Arabidopsis)
> Arabidopsis$fruits <- factor(Arabidopsis$total.fruits > 0)
> Arabidopsis$gengr <- cut(Arabidopsis$gen, c(0,15,26,40))
> 
> explanatory = c("gengr","rack","nutrient","amd","status")
> dependent = "fruits"
> random_effect = "popu"
> 
> Arabidopsis %>%
+ 	ff_glimpse(dependent, c(explanatory, random_effect))
$Continuous
            label var_type   n missing_n missing_percent mean  sd min quartile_25 median quartile_75 max
rack         rack    <int> 625         0             0.0  1.5 0.5 1.0         1.0    1.0         2.0 2.0
nutrient nutrient    <int> 625         0             0.0  4.6 3.5 1.0         1.0    8.0         8.0 8.0

$Categorical
        label var_type   n missing_n missing_percent levels_n                                             levels  levels_count levels_percent
fruits fruits    <fct> 625         0             0.0        2                       "FALSE", "TRUE", "(Missing)"      126, 499         20, 80
gengr   gengr    <fct> 625         0             0.0        3        "(0,15]", "(15,26]", "(26,40]", "(Missing)" 216, 220, 189     35, 35, 30
amd       amd    <fct> 625         0             0.0        2                "clipped", "unclipped", "(Missing)"      303, 322         48, 52
status status    <fct> 625         0             0.0        3 "Normal", "Petri.Plate", "Transplant", "(Missing)"  377, 91, 157     60, 15, 25
popu     popu    <fct> 625         0             0.0        9                                                  -             -              -

> 
> Arabidopsis %>%
+ 	finalfit(dependent, explanatory, random_effect = random_effect, keep_fit_id = TRUE, cont_cut = 1) %>%
+ 	ff_merge(
+ 	  explanatory %>%
+ 	    purrr::map_df(~ glmmixed(Arabidopsis, dependent, .x, random_effect = random_effect) %>%
+ 	      fit2df(estimate_suffix = " (univariable with RE)")),
+ 	        last_merge = TRUE
+ 	) %>%
+ 	dplyr::relocate(7, .before = 6)
Waiting for profiling to be done...
Waiting for profiling to be done...
Waiting for profiling to be done...
Waiting for profiling to be done...
Waiting for profiling to be done...
   Dependent: fruits                 FALSE       TRUE          OR (univariable)  OR (univariable with RE)            OR (multilevel)
3              gengr      (0,15]  21 (9.7) 195 (90.3)                         -                         -                          -
4                        (15,26]   8 (3.6) 212 (96.4) 2.85 (1.28-6.99, p=0.014) 2.61 (0.68-9.99, p=0.161) 2.54 (0.58-11.17, p=0.218)
5                        (26,40] 97 (51.3)  92 (48.7) 0.10 (0.06-0.17, p<0.001) 0.18 (0.05-0.63, p=0.007)  0.12 (0.03-0.50, p=0.004)
7               rack   Mean (SD) 1.7 (0.5)  1.4 (0.5) 0.43 (0.28-0.64, p<0.001) 0.35 (0.22-0.58, p<0.001)  0.30 (0.17-0.51, p<0.001)
6           nutrient   Mean (SD) 3.7 (3.4)  4.8 (3.5) 1.10 (1.04-1.16, p=0.002) 1.17 (1.09-1.25, p<0.001)  1.18 (1.10-1.28, p<0.001)
1                amd     clipped 75 (24.8) 228 (75.2)                         -                         -                          -
2                      unclipped 51 (15.8) 271 (84.2) 1.75 (1.18-2.61, p=0.006) 2.40 (1.48-3.90, p<0.001)  2.91 (1.70-4.99, p<0.001)
8             status      Normal 60 (15.9) 317 (84.1)                         -                         -                          -
9                    Petri.Plate 19 (20.9)  72 (79.1) 0.72 (0.41-1.30, p=0.258) 0.38 (0.19-0.75, p=0.005)  0.28 (0.13-0.60, p=0.001)
10                    Transplant 47 (29.9) 110 (70.1) 0.44 (0.29-0.69, p<0.001) 0.71 (0.41-1.23, p=0.222)  0.67 (0.37-1.22, p=0.194)
```
