### ISSUE TITLE
Exporting .png

### ISSUE THREAD

**Issue by davidhen** [ewenharrison/finalfit#16]
Hi Ewan,

Is it possible to export the results of `or_plot()` as a .png? 

I am working in the safe haven so not writing reports/thesis in there but exporting all plots/tables and embedding them in .pdf manually (I know!!).  

Anyhow, when I try....(`reprex` won't let me change the plot width so a bit squashed here, but my actual plot looks ok)

``` r
  
library(finalfit)

explanatory <- c("age.factor", "sex.factor", "obstruct.factor", "perfor.factor")
dependent <- 'mort_5yr'
colon_s %>%
  or_plot(dependent, explanatory)
#> Waiting for profiling to be done...
#> Waiting for profiling to be done...
#> Waiting for profiling to be done...
#> Warning: Removed 4 rows containing missing values (geom_errorbarh).
```

![](https://i.imgur.com/BVi9Z1h.png)

<sup>Created on 2019-03-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

...and then 

``` r
library(ggplot2)
ggsave(filename = "or_plot_test.png", width = 9, height = 6.75, dpi = 600)
```

<sup>Created on 2019-03-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

....The resulting .png looks like.....

![or_plot_test](https://user-images.githubusercontent.com/26236404/53801809-1421f900-3f38-11e9-93fc-b4298731dfde.png)

I've tried fiddling with widths and heights etc. Is there anything else I could do to get the plot to render correctly in the .png??

Edit - I just tried exporting to .pdf instead with the same results

**Comment by ewenharrison** [comment]
Thanks David. The output is not a simple ggplot, given the table is added. So that is why that probably won't work. Can you do it with the traditional approach in your environment?
```
png('or_plot_test.png', width = 600, height = 500)
colon_s %>%
  or_plot(dependent, explanatory)
dev.off()
```

**Comment by davidhen** [comment]
Yes!! 

This does it, thanks very much!!

David

**Comment by davidhen** [comment]
Yes, this certainly works on my own machine, thanks!!
