### ISSUE TITLE
Feature Request: total_col for numeric variables

### ISSUE THREAD

**Issue by nrkoehler** [ewenharrison/finalfit#17]
Would you consider making the `total_col` argument of the `summary_factorlist()` function work for numeric variables? So far, this argument works for factors (and maybe character vars) only. Thanks in advance, Norbert

**Comment by ewenharrison** [comment]
Thanks. This is done. Let me know if it doesn’t do what you expect/want.

**Comment by nrkoehler** [comment]
Oh, thanks a lot - that was quick! :-) I have just installed version 0.9.1 and it works. Best regards, Norbert

**Comment by nrkoehler** [comment]
Sorry, but I just discovered that the `column_total` option of the `summary_factorlist()` function does work for numeric variables as I expected. I would like the the function to return mean and standard deviation (or median and IQR) for the whole sample. Instead it returns the number and percentages of non-missing values. Best regards, Norbert

**Comment by ewenharrison** [comment]
Thanks Norbert. Ah I see now what you were asking for. That is not planned at the moment, but we will bear in mind for the next re-write. Thank you again.

**Comment by nrkoehler** [comment]
Ok, thank you!

**Comment by ewenharrison** [comment]
This is now done in 0.9.2

**Comment by nrkoehler** [comment]
Thanks a lot!
