### ISSUE TITLE
Zero events in summary tables

### ISSUE THREAD

**Issue by graemeleehickey** [ewenharrison/finalfit#18]
When making a table using a `summary_factorlist()`, I passed a large list of explanatory variables, and the function threw and error because one of the variables had zero events in all arms. Is there a way to still include this variable in the table? Or at the very least throw an informative error message so it is clear which variable is causing the problem?

**Comment by ewenharrison** [comment]
Thanks for these Graeme. 
It would help if you could make some toy data that demonstrates the problem and also include the error.

**Comment by graemeleehickey** [comment]
The following example works in `finalfit`:

```
library(finalfit)
library(dplyr)
data(colon_s)

explanatory <- c("age", "age.factor", "sex", "obstruct.factor")
dependent <- "perfor.factor"
colon_s %>%
  summary_factorlist(dependent, explanatory, p = TRUE)
```

However, from time to time you may have a binary variable (e.g. in a subgroup analysis with a low prevalence covariate) where all values are zero. In this case, `summary_factorlist()` throws an error:

```
colon_s$sex2 <- 0
explanatory <- c("age", "age.factor", "sex2", "obstruct.factor")
dependent <- "perfor.factor"
colon_s %>%
  summary_factorlist(dependent, explanatory, p = TRUE)
```

Confusingly, the function still works in the following case where you have a factor with only 1 unique level:
```
colon_s$sex.factor2 <- factor("Female")
explanatory <- c("age", "age.factor", "sex.factor2", "obstruct.factor")
dependent <- "perfor.factor"
colon_s %>%
  summary_factorlist(dependent, explanatory, p = TRUE)
```

**Comment by ewenharrison** [comment]
Thanks for your continued help with this Graeme. I don't think I'm seeing what you are seeing with this. Seems ok to me: 
```
> colon_s$sex2 <- 0
> explanatory <- c("age", "age.factor", "sex2", "obstruct.factor")
> dependent <- "perfor.factor"
> colon_s %>%
+ 	summary_factorlist(dependent, explanatory, p = TRUE)
        label      levels          No         Yes     p
1 Age (years)   Mean (SD) 59.8 (11.9) 58.4 (13.3) 0.578
2         Age   <40 years   68 (97.1)     2 (2.9) 1.000
3             40-59 years  334 (97.1)    10 (2.9)      
4               60+ years  500 (97.1)    15 (2.9)      
7        sex2           0  902 (97.1)    27 (2.9)    NA
8                       1     0 (NaN)     0 (NaN)      
5 Obstruction          No  715 (97.7)    17 (2.3) 0.018
6                     Yes  166 (94.3)    10 (5.7)      
Warning message:
In chisq.test(tab, correct = FALSE) :
  Chi-squared approximation may be incorrect
```
