### ISSUE TITLE
P-values when showing missing data

### ISSUE THREAD

**Issue by graemeleehickey** [ewenharrison/finalfit#20]
In `summary_factorlist()`, if missing data rows are reported for categorical data, the P-value comparing 2 groups treats this as an additional level. Is it possible to report the missing data, without changing the P-values?

**Comment by ewenharrison** [comment]
Yes. Though it would need to be clear this was happening. There may be instances when people want to compare over the missing level. At the moment in our own workflow we produce a table including missing table, then manually adjust p-values to reflect only the complete data. 
So agree, this would be useful.

**Comment by ewenharrison** [comment]
It's been a little while, but the soon to be released 1.0.0 deals with this issue. Currently available from Github. 

Default behaviour is now that missing data is not passed to hypothesis tests. The argument `na_to_p = TRUE` allows this to happen if desired. Which is likely to be rarely, as making the missing explicit in the data would be safer `forcats::fct_explicit_na`
