### ISSUE TITLE
Total column for continuous variables

### ISSUE THREAD

**Issue by graemeleehickey** [ewenharrison/finalfit#21]
When `total_col = TRUE` in `summary_factorlist()`, continuous variables are reported as NA rather than the mean (SD).

**Comment by ewenharrison** [comment]
If you update the package, the total column currently shows the total `n` represented in that continuous variable and a proportion if there is missing data. This has suited the needs of the `total` column. There has been another request for a mean/median in that column but that is not currently planned. We will look at it again.

**Comment by ewenharrison** [comment]
This is done 0.9.2
