### ISSUE TITLE
No support for non-integer explanatory variables?

### ISSUE THREAD

**Issue by LukaszDerylo** [ewenharrison/finalfit#27]
Let's create toy dataset:

    set.seed(1)
    dat<-data.frame(
       y=rnorm(10),
       x1=gl(2,5, labels=c("A","B")),
       x2=(1:10)
     )

And use `finalfit` with `y` as dependent variable:

    dat %>% finalfit.lm(dependent =  'y', explanatory =  c('x1','x2'))

      Dependent: y         Mean (sd)      Coefficient (univariable)    Coefficient (multivariable)
    1           x1      A  0.4 (0.8)                              -                              -
    2                   B -0.4 (1.1) -0.84 (-2.24 to 0.56, p=0.205) -2.19 (-4.99 to 0.60, p=0.106)
    3           x2 [1,10]  0.0 (1.0) -0.06 (-0.33 to 0.21, p=0.610)  0.27 (-0.22 to 0.76, p=0.230)

So far so good. But when I make `x2` non-integer, the same code fails:

    set.seed(1)
    dat<-data.frame(
       y=rnorm(10),
       x1=gl(2,5, labels=c("A","B")),
       x2=(1:10)/10
     )
     dat %>% finalfit.lm(dependent =  'y', explanatory =  c('x1','x2'))

    Error in if (cj == upper) next : missing value where TRUE/FALSE needed

I tried several other integer and non-integer expalnatory variables. Results are the same.

What am I missing?

**Comment by ewenharrison** [comment]
Thank you for this. 

I can' reproduce this on my server version. What system are you using?
Are your packages up-to-date?
You could start by trying: 
` devtools::install_github('ewenharrison/finalfit')`

```
dat<-data.frame(
 y=rnorm(10),
 x1=gl(2,5, labels=c("A","B")),
 x2=(1:10)/10
)

dat %>% 
 finalfit('y', c('x1','x2'))
Dependent is not a factor and will be treated as a continuous variable
  Dependent: y         Mean (sd)     Coefficient (univariable)    Coefficient (multivariable)
1           x1       A 0.1 (1.0)                             -                              -
2                    B 0.1 (0.7) 0.01 (-1.20 to 1.21, p=0.991) -1.10 (-3.54 to 1.33, p=0.319)
3           x2 [0.1,1] 0.1 (0.8) 0.55 (-1.51 to 2.60, p=0.556)  2.22 (-2.02 to 6.46, p=0.255)
```

Please let me know how you get on. 
Ewen

**Comment by LukaszDerylo** [comment]
Thank you, I've updated all the packages I have (`finalfit` was already up to date), and now it works.

**Comment by ewenharrison** [comment]
Thank you. It was probably `Hmisc`.
