### ISSUE TITLE
`ff_percent_only()` and p-values

### ISSUE THREAD

**Issue by larmarange** [ewenharrison/finalfit#31]
When computing p-value with `summary_factorlist()` and using `ff_percent_only()`, p-values are transformed into NA

```r
explanatory = c("age", "age.factor", "sex.factor", "obstruct.factor")
dependent = "perfor.factor"
colon_s %>%
  summary_factorlist(dependent, explanatory, p=TRUE) %>%
  ff_percent_only()
```

```
        label      levels          No         Yes     p
1 Age (years)   Mean (SD) 59.8 (11.9) 58.4 (13.3) 0.578
2         Age   <40 years         7.5         7.4  <NA>
3             40-59 years        37.0        37.0  <NA>
4               60+ years        55.4        55.6  <NA>
5         Sex      Female        47.9        48.1  <NA>
6                    Male        52.1        51.9  <NA>
7 Obstruction          No        81.2        63.0  <NA>
8                     Yes        18.8        37.0  <NA>
```

The problem is maybe that you remove the number of observations after the computation of `summary_factorlist()` and it could be difficult to consider all the different use scenarios.

Maybe, it could be easier to consider instead an option directly within `summary_factorlist()` indicating how n and % should be presented? For allowing an high flexibility, you could use the syntax of `str_glue()`. For example an argument `cat_format` with default value equal to `"{n} ({percent})"`.  It would be very easy for users to adapt the output.

**Comment by ewenharrison** [comment]
Thanks Joseph. 
The philosophy recently on all the bespoke requests we get is to try and not touch the underlying functions. Obviously this sometimes needs to be done, but if, say "can we have percentages only" can be done without adding yet more arguments to the base function, then that might be seen as a good thing. 
The formatting is a good idea and something we will look at. It would require some significant rewrites of underlying functions. 
This particular issue is fixed for now. 
Much appreciated.
