### ISSUE TITLE
data name, dependent variable and explanatory variable as attributes

### ISSUE THREAD

**Issue by larmarange** [ewenharrison/finalfit#32]
Just a comment regarding function such as `ff_column_totals()` or `ff_row_totals()`:

To facilitate the use of these functions, it could be relevant that `summary_factorlist()` adds to the output some attributes (using `attr()`) to store dependent and explanory variables as well as the name of the dataset. Therefore, functions as `ff_row_totals()` could, as default values, directly read these attributes.

**Comment by ewenharrison** [comment]
Yes its a good thought. Our experience in general with attributes is that they often get stripped inadvertently by other functions, or cause unexpected side-effects. Even labelling variable names caused huge difficulty with haven. We now don't change the class on the variable (previous inherited "labelled") as that was causing problems with other tidyverse functions (such as glimpse). 
Good thought though.

**Comment by larmarange** [comment]
It's true that sometimes attributes get lost. 
However, in that case where finalfit's functions will use in a pipeline, it should be OK.

Regards
