### ISSUE TITLE
Splitting `ff_row_totals()` in 2 functions

### ISSUE THREAD

**Issue by larmarange** [ewenharrison/finalfit#33]
`ff_row_totals()` does two things: it adds row totals and the number of missing values. But sometimes, you do not need to present missing values (or you do not have them).

It could be worth therefore to have instead two functions `ff_row_totals_without_missing()` and `ff_row_totals_with_missing()`.

Best regards

**Comment by ewenharrison** [comment]
This is done. Thank you.
