### ISSUE TITLE
NAs in column containing parameter values when condense=F

### ISSUE THREAD

**Issue by LukaszDerylo** [ewenharrison/finalfit#35]
It would be nice to have NAs in column containing parameter values when condense=F. Now we have "-" there which forces this column to be of `character` type instead of (desired) `numeric`.

**Comment by ewenharrison** [comment]
Thank you for this. 
The workaround for this is below. It may be useful to include this in `finalfit()` but it won't be included at the moment. Let me know if you have any issues. Note you need to be on the github version of ff.

```
library(finalfit)
explanatory = c("age.factor", "sex.factor", "obstruct.factor", "perfor.factor")
dependent = 'mort_5yr'
colon_s %>%
  summary_factorlist(dependent, explanatory, fit_id = TRUE) %>% 
  ff_merge(
    glmmulti(colon_s, dependent, explanatory) %>% 
      fit2df(condense = FALSE), 
    ref_symbol = 1, last_merge = TRUE)%>% str()
```

**Comment by LukaszDerylo** [comment]
OK, thank you. For now I simply use `na_if` to turn `-`'s to NAs
