### ISSUE TITLE
Error with missing_compare

### ISSUE THREAD

**Issue by mcabran** [ewenharrison/finalfit#36]
Hi, I am currently conducting an analysis of missing data for my MA dissertation using the `finalfit `package.  I am having some issues with the function `missing_compare`. I have posted a full description [here](https://stackoverflow.com/questions/58843745/error-in-finalfitmissing-compare-does-not-find-an-object).  `ff-glimpse`, `missing_pairs` and `finalit `functions do actually work.
Anyway, my code is the following
```
explanatory_edu  <- c("ch_edu", "a4g")
dependent <- "br"
sl_cfa %>% 
  missing_compare(dependent, explanatory_edu)
```
and I am getting the following error message
```
> sl_cfa %>% 
+   missing_compare(dependent, explanatory_edu)
Error in factor(g, levels = unique(g)) : object 'g' not found
```
All three variables are dichotomous factors without labels
```
> str(sl_cfa$br)
 Factor w/ 2 levels "0","1": NA 2 2 1 1 NA 2 2 1 1 ...
> str(sl_cfa$ch_edu)
 Factor w/ 2 levels "0","1": 1 2 NA 1 1 NA 1 1 2 1 ...
> str(sl_cfa$a4g)
 Factor w/ 2 levels "0","1": NA 1 NA NA NA NA 1 2 1 2 ...
```

**Comment by ewenharrison** [comment]
Thanks. 
https://stackoverflow.com/questions/58843745/error-in-finalfitmissing-compare-does-not-find-an-object/58905267#58905267

**Comment by mcabran** [comment]
Thanks, that worked just fine! One additional question, is there any guideline / rule of thumb on how to interpret the p values (with all the caveat of interpreting p values, of course)? Something like: > 0.05 is MCAR, between 0 and 0.05 is MAR, below 0 is MNAR? (I am just making up these values to give an idea).

**Comment by ewenharrison** [comment]
Thanks. No, the p-value cannot be interpretted in that way I'm afraid. All you can say is that the data appear NOT to be MCAR, and therefore may be MAR or MNAR.
