### ISSUE TITLE
"Univariable" and "multivariable" unclear

### ISSUE THREAD

**Issue by thelittlerock** [ewenharrison/finalfit#38]
In the [documentation](https://finalfit.org/articles/finalfit.html), the logistic regression with reduced model output is said to contain "a multivariable model contains a subset of the variables included specified in the full univariable set."

This use of language is odd, because _univariable_ typically means that there is only one explanatory variable, whereas _multivariable_ means that there are several explanatory variables ([Tsai, 2013](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3679183/)).

Would it be helpful to change this terminology or allow users to alter the default language?

**Comment by ewenharrison** [comment]
Many thanks for this. 
Happy to take a suggested change. 
There are a set of variables used for univariable analyses and a subset specified for a parsimonious model. It seems clear to me. Thanks again.
