### ISSUE TITLE
passing imputed coxph model to hr_plot via coxfit not working

### ISSUE THREAD

**Issue by KMBHPB** [ewenharrison/finalfit#39]
Hi Ewan, 

Once again, great package which continues to prove itself as being extremely useful.

I would like to produce an HR plot using the pooled coxph results from `mice::pool()` via the  `coxfit` option in `hr_plot`.

I have been able to the same in a separate OR plot via `glmfit = fits_pool` as per your example, but I cannot find a way to make the same work for the HR plot. 

It gives the error; "object 'HR' not found" - it seems possibly to do with coxfit calling on fit2df looking for an estimate name 'HR'??

`survcomp::forestplot.surv` uses a set of user-specified vectors as its input, which would work, but the format is not as nice and I would rather keep it all in finalfit if possible.

Any suggestions would be appreciated.

Cheers,

Kai

**Comment by ewenharrison** [comment]
Thanks Kai.
Yes I did or_plot but didn't do hr_plot.
I will do.
Thanks again.

**Comment by KMBHPB** [comment]
Thanks, Ewan, amazing. Commendable ongoing input to feature enhancement

**Comment by ewenharrison** [comment]
This works for me with no changes to current functions. Does it do what you need or is it not working? If not working, I'd love if you could provide a reprex of the issue. 
Thanks again for your help. 

```
# Multivariate Imputation by Chained Equations (mice)
library(finalfit)
library(dplyr)
library(mice)
explanatory = c("age.factor", "sex.factor", "obstruct.factor", "perfor.factor")
dependent = "Surv(time, status)"

# Predictor matrix
colon_s %>% 
  select(explanatory) %>% 
  missing_predictorMatrix() -> predM

# Run model
fits = colon_s %>% 
  mice(m = 4, predictorMatrix = predM) %>% 
  with(survival::coxph(formula(ff_formula(dependent, explanatory))))

# Pool  results
fits_pool = fits %>% 
  pool() %>% 
  fit2df(exp = TRUE)

## Can be passed to or_plot
colon_s %>% 
  hr_plot(dependent, explanatory, glmfit = fits_pool, table_text_size=4)
```

**Comment by ewenharrison** [comment]
Hi,
Can you pull from github and see if this is now working.

```
devtools::install_github("ewenharrison/finalfit")
```
This now works for me:
```
# Multivariate Imputation by Chained Equations (mice)
library(finalfit)
library(dplyr)
library(mice)
library(survival)
explanatory = c("age.factor", "sex.factor", "obstruct.factor", "perfor.factor")
dependent = "Surv(time, status)"

# Predictor matrix
colon_s %>% 
  select(explanatory) %>% 
  missing_predictorMatrix() -> predM

# Run model
fits = colon_s %>% 
  mice(m = 4, predictorMatrix = predM) %>% 
  with(coxph(formula(ff_formula(dependent, explanatory))))

# Pool  results
fits_pool = fits %>% 
  pool()

## Can be passed to hr_plot
colon_s %>% 
  hr_plot(dependent, explanatory,  coxfit = fits_pool, table_text_size=4)
```

**Comment by KMBHPB** [comment]
Hi Ewan, 

I can confirm that the GitHub version is working perfectly and drawing the HR plot from the imputed data.

Thanks for your speedy fix.

Cheers,

Kai
