### ISSUE TITLE
Quantitative variable disappearing in hr_plot when remove_ref is TRUE

### ISSUE THREAD

**Issue by rriem** [ewenharrison/finalfit#47]
I've noticed that in recent versions of finalfit (at least 1.0.1), quantitative variables (eg AGE) don't appear in **hr_plot** when I set the _remove_ref_ option to TRUE, but do appear when _remove_ref_ is set to FALSE.

Did I miss something ?

Sincerly yours

Romuald Riem

**Comment by ewenharrison** [comment]
Thank you!
I think this should be fixed in the current Github version?

**Comment by rriem** [comment]
Thanks very much for this prompt answer.

I shoud have try the latest github version before opening a new issue.

Sorry.

Indeed, it looks like it works as expected.

Romuald Riem
