### ISSUE TITLE
Check speed and Code Refactor

### ISSUE THREAD

**Issue by Nelson-Gon** [ewenharrison/finalfit#50]
Hello,

I noticed that the builds on Travis take quite some time as do the local checks. For instance:

```r
checking examples (4m 9.9s)
   Examples with CPU (user + system) or elapsed time > 5s
                       user system elapsed
   ff_permute         37.63   0.14   54.54
   finalfit           22.25   0.09   26.56
   ff_remove_ref      10.01   0.04   11.97
   ff_plot             9.39   0.06   13.00
   ff_merge            7.47   0.05    8.33
   or_plot             7.43   0.08    8.89
   boot_predict        7.17   0.32    8.93
   dependent_label     7.02   0.14    9.23
   fit2df              6.19   0.11    6.50
   ff_stratify_helper  5.08   0.04    5.86
   hr_plot             4.58   0.06    5.24
   surv_plot           3.31   0.40    5.33
```
Is there a way to speed these up?

Secondly, I noticed that some code is quite repetitive and was wondering whether helpers could be written for these and perhaps this might reduce the execution time(especially for the multiple `apply` calls).

Thank you,

Nelson

**Comment by ewenharrison** [comment]
Many thanks for your help, suggestions DBD the pull request. 
We’re snowed under with Covid-19 work at the moment so won’t be making big changes to underlying code. We’d be delighted if you wanted to benchmark any improvements in code speed with changes. Some things do take longer with our dplyr approach than they would using, say, data.table. But we’re never slowed down by Finalfit code, usually only necessarily by underlying functions such as glmer. Most Finalfit code is instantaneous for data of 100Ks lines. Maybe if you are in millions there could be issues. Thanks again.
