### ISSUE TITLE
Error "contrasts can be applied only to factors with 2 or more levels" with missing_compare and finalfit()

### ISSUE THREAD

**Issue by BTessoulin** [ewenharrison/finalfit#51]
Hi, 
I'd like to thank you for your finalfit package, I had started by myself for Cox and GLM, but your routine is so nicely done with the graphic representation that I couldn't compete and I adopted it! 

I got an issue with the followings missing_compare() and finalfit(), while having no problems with missing_plot():
> test

  | pa02 | p.f | hte_conc_o2 | VM | ICU | surv_d90
-- | -- | -- | -- | -- | -- | --
  | <dbl> | <dbl> | <fct> | <fct> | <fct> | <fct>
1 | 6.1 | 218 | yes | yes | yes | 1
2 | 9.3 | 332 | yes | no | yes | 0
3 | 7.3 | 261 | no | no | no | 0
4 | NA | NA | yes | yes | yes | 0
5 | NA | NA | yes | no | yes | 0
6 | NA | NA | yes | no | yes | 0
7 | NA | NA | no | no | no | 0
8 | 10.7 | 382 | yes | no | yes | 0
9 | NA | NA | yes | yes | yes | 1
10 | 6.8 | 243 | yes | yes | yes | 0

When I use the finalfit(dependent,explanatory) for every variable I got no problem, for instance:
`test%>%finalfit("surv_d90","ICU")`

Dependent: | surv_d90 |   | 0 | 1 | OR (univariable) | OR   (multivariable)
-- | -- | -- | -- | -- | -- | --
  | ICU | no | 128 (89.5) | 15 (10.5) | - | - |  
  |   | yes | 99 (59.3) | 68 (40.7) | 5.86 (3.24-11.22, p<0.001) | 5.86 (3.24-11.22, p<0.001)

I can create a loop that goes through all the explanatory variables, without fatal error, but when I use the finalfit() or missing_compare() code for all explanatory variables:

Error: Tibble columns must have consistent lengths, only values of length one are recycled:

* Length 6: Column `p`
* Length 8: Columns `explanatory`, `estimate`, `confint[, 1]`, `confint[, 2]`
Run `rlang::last_error()` to see where the error occurred.
In addition: There were 26 warnings (use warnings() to see them)

 I've tried to implement the data.frame as Tibble was involved, without succes either
`test%>%
data.frame%>%
finalfit("surv_d90",explanatory)`

Thank you for your help, and sorry if I missed some important point! 

benoit

**Comment by ewenharrison** [comment]
You shouldn't need a loop to for explanatory variables. 
```
test %>% 
  finalfit("surv_d90", c("ICU", "VM"))
```
