### ISSUE TITLE
footnote for crosstable (summary_factorlist) showing hypothesis test names of corresponding p-values

### ISSUE THREAD

**Issue by sbalci** [ewenharrison/finalfit#52]
Dear developers,

I went through the code but could not find an option for this.

It would be nice to have hypothesis test names of corresponding p-values as a footnote when using summary_factorlist.

Best wishes.

**Comment by ewenharrison** [comment]
Thanks Serdar.
As you know, we have kept all tables as data frames or tibbles in finalfit to be as flexible as possible in output. The question would be how to do that and stay so flexible (one of the benefits of finalfit in my humble opinion!). `finalfit(..., metrics = TRUE)` has a second data frame with model information and the two are returned as a list. But even this creates an extra step for users separating them. 
Interested in your thoughts.

**Comment by sbalci** [comment]
Hi Ewen,

I continue to try to add some functions to jamovi as a module. While working on crosstables I wanted to compare some similar packages. I added tangram, arsenal, gtsummary and finalfit. Then I realised that the p-values are different. See below images.

**FinalFit:**
<img width="537" alt="finalfit" src="https://user-images.githubusercontent.com/7208830/85140839-85c9a780-b24e-11ea-803e-452516324e68.png">

**gtsummary:**
<img width="526" alt="gtsummary" src="https://user-images.githubusercontent.com/7208830/85140863-924e0000-b24e-11ea-9696-9b7059a9d6a6.png">

**tangram:**
(is currently under update in with recent commit p-values are gone, probably will be fixed soon)
<img width="543" alt="tangram" src="https://user-images.githubusercontent.com/7208830/85140877-9843e100-b24e-11ea-97ba-2f7e41f0d6e4.png">

**arsenal:**
<img width="582" alt="arsenal" src="https://user-images.githubusercontent.com/7208830/85140896-9ed25880-b24e-11ea-99d4-7fe76d22127e.png">


The problem is that users are ready to accept these results as publication ready and I wanted to add the test names. I think the packages use different tests and I tried to dig into codes. tangram (as default and text), arsenal as an argument, and gtsummary as an optional function gives the names of functions. I could not add arsenal's test names due to html output structure (https://github.com/mayoverse/arsenal/issues/298).

- For the `metrics = TRUE` I tried to add it to multivariate survival function, the output is skewed, but it can be worked on.

<img width="560" alt="Ekran Resmi 2020-06-19 17 29 21" src="https://user-images.githubusercontent.com/7208830/85143559-92e89580-b252-11ea-8c0c-1e8a4fc9406c.png">

- If the output is a list and I can extract them as result[["table"]] and results[["footnote"]] it will be easy to implement. 

- Or, to keep dataframe output, you may consider adding another column for test names and include it optional argument similar to `p = TRUE` something like `testname = TRUE`. This way you may get rid of pasting asteriks, symbols or numbers to p-value. And with another function footnote can be generated via combining variable name and testname from dataframe output.

Thank you for your time.

**Comment by ewenharrison** [comment]
Thanks. There is a choice of tests with `summary_factorlist` that can be specified. So it kind of depends what the user wants to do. Are you utilising the various column and row summarising arguments? Let me know if anything is not clear in the documentation and I can adjust.

**Comment by sbalci** [comment]
Then I can add the arguments as options to the user interface and depending on the selected one I can add test names and I can add a link to the [documentation](https://finalfit.org/reference/summary_factorlist.html)

`cont = "mean", cont_nonpara = NULL, p_cont_para = "aov", p_cat = "chisq"`

Thank you :) I will let you know the updates.
