### ISSUE TITLE
Use univariate analysis in hr_plot plot and add subgroups

### ISSUE THREAD

**Issue by Tato14** [ewenharrison/finalfit#53]
First, thanks for the great tool!

I guess  univariate results are not the proper ones to show in a forest plot but I would like to see the comparison between both univariate and multivariate. Could it be possible to add an option to this in `hr_plot`? As a quick workaround I guess it could be easy  to parse `coxphuni` table as a source for `hr_plot`, right?

Also, I was wondering how subgroups could be plotted in  the same forest plot. Something like I have HR for the whole cohort and then HR for specific subgroups (treatment A and treatment B). Would be great to have them all plotted in the same image. Something like [this](https://stackoverflow.com/questions/34265594/legend-in-a-forest-plot) or [this](http://www.strengejacke.de/sjPlot/reference/plot_models.html)

**Comment by ewenharrison** [comment]
Thanks for your comments. 
We try to make everything possible not not include a bewildering set of options. 
So there are no plans to include the option to make univariable forest plots for the reasons you say. 

But it is quite straightforward to do and the same method for groups. 

```
p_uni = colon_s %>%
  coxphuni(dependent, explanatory) %>% 
  hr_plot(colon_s, dependent, explanatory, coxfit = .,
          breaks = c(0.5, 1, 1.5, 2),
          dependent_label = "Survival (univariable)", suffix = "",
          plot_opts=list(xlab(""),
                         expand_limits(x = c(0.5, 2.0))))
p_multi = colon_s %>%
  hr_plot(dependent, explanatory,
          breaks = c(0.5, 1, 1.5, 2),
          dependent_label = "Survival (multivariable)", suffix = "",
          plot_opts=list(expand_limits(x = c(0.5, 2.0))))

ggpubr::ggarrange(p_uni, p_multi, ncol = 1)
```

![image](https://user-images.githubusercontent.com/3391394/86457852-3c805a00-bd1c-11ea-9cba-0a4a1771cacd.png)

**Comment by Tato14** [comment]
Thanks for the quick feedback!

Regarding subgroups, I was hoping to add each subgroup in each comparison *inside* the same plot (and colour them differently) rather than create plots for every condition. 

Something like:
![image](https://user-images.githubusercontent.com/33808607/86461693-aacc1900-bd2a-11ea-95a9-6551b7712a13.png)
extracted from [here](https://stackoverflow.com/questions/34265594/legend-in-a-forest-plot).

Guess I should add `geom_errorbarh` for every condition and pass it to `plot_opts` but I am unsure how to place them in each specific condition.

**Comment by ewenharrison** [comment]
Multiple different models within the same plot is not currently supported. Thanks again.
