### ISSUE TITLE
Can you do a weighted Cox PH in finalfit?

### ISSUE THREAD

**Issue by ob325** [ewenharrison/finalfit#55]
Hi,
Using finalfit::coxphmulti(), is it possible to pass additional parameters to the underlying survival::coxph() function, in particular the "weights" argument? The use case would be running a survival model for a population that is already balanced between treatment vs. control groups using inverse probability of treatment weighting.

Thanks.

**Comment by ewenharrison** [comment]
Thanks Bill. 
If you pull the dev version from github you should now be able to include a `weights` argument. 
This was done for GLM in the past but never written in for CPH. 
Thanks again. Let me know if you have problems.
