### ISSUE TITLE
OR and P value dont appears in or_plot

### ISSUE THREAD

**Issue by gagonzalezm** [ewenharrison/finalfit#61]
Hi, 
First of all, 
Thank you very much for this package, I have been learning about it since a week. 
I have a problem that I did not have with other data.  
When I do the OR plot the middle column in the plot with or and p values dont appear. I think it could be associated with dimensions of the table, however i dont know which options change to get it, i think it could be related with plot_opts, or table_opts, but in documentation not information is provided about that arguments

The problem is only in or_plot, when i create the summary table with finalit i dont have problems. 

![image](https://user-images.githubusercontent.com/63219253/100393149-788fc080-3017-11eb-8aea-c22a22adae53.png)

## Coding
or_plot <- dat %>%
  or_plot(dependent, explanatory,
          table_text_size=3, title_text_size=11,
          column_space = c(-2, 0, 2),
          dependent_label = "Alguna experiencia psicótica en la vida ",
          plot_opts=list(xlab("OR, 95% CI"), 
                         theme(axis.title = element_text(size=8)
                         )
          )
  )

**Comment by ewenharrison** [comment]
Is your dependent variable binary and coded as a factor?

**Comment by gagonzalezm** [comment]
Thank you very muchb Ewen for your fast response. I have created my variable as a factor with 2 levels collapsing numbers from other variables, but i forget a number, then, It was the problem, the NA cases were coded as a third category, and my variable not was binary as I was thinking.

Here my plot now. all is good! 
Regards.

![image](https://user-images.githubusercontent.com/63219253/100664492-72ab1f80-3336-11eb-8d3d-74c02894c0c7.png)
