### ISSUE TITLE
How to save plots?

### ISSUE THREAD

**Issue by skycrazer** [ewenharrison/finalfit#62]
Is there a way to save plots from finalfit? ggsave provides very odd results.
Thanks
Tanjit

**Comment by ewenharrison** [comment]
Thanks. Just in the standard way. Let me know if it doesn't work on your system.  

```
explanatory = c("age.factor", "sex.factor", "obstruct.factor", "perfor.factor")
dependent = "mort_5yr"

pdf(file = "or_plot.pdf", width = 14, height = 7)
colon_s %>%
  or_plot(dependent, explanatory)
dev.off()

png(file = "or_plot.png", width = 800, height = 400)
colon_s %>%
  or_plot(dependent, explanatory)
dev.off()
```

**Comment by skycrazer** [comment]
Thank you! Works perfectly!

Am Sa., 5. Dez. 2020 um 15:51 Uhr schrieb ewenharrison <
notifications@github.com>:
