### ISSUE TITLE
Error with Labels for Continuous Variables

### ISSUE THREAD

**Issue by adam-mdmph** [ewenharrison/finalfit#65]
I have an issue that summary_factorlist keeps giving me the same error if I add a label to a numeric variable.  The code works fine with labels on factors and with numeric variables without a label.  Here is the code I use to add a label and then run the summary_factorlist function.  Thanks for any help you can provide.

`label(STF3$OCCLEN_FP) <- "Occlusion Length"'`

`vasc = c("INDICATION", "CALC_FP", "TASC_FP", "OCCLEN_FP", "TISSUELOSS_SEV_FP", "INFECTION_FP", "PRIOR_AMP_FP", "PREOP_TOEPRESSURE_FP", "PREOP_ABI_FP", "RUNOFF_EXP", "ISR_FP")`

`STF3 %>%
  summary_factorlist(obl, vasc, cont = "median", column = T, p=TRUE, total_col = T ) -> table_obl_vasc`

Error: Problem with `summarise()` input `value_median`.
x Input `value_median` must return compatible vectors across groups
ℹ Result type for group 1 (OBL = "Hospital"): <labelled>.
ℹ Result type for group 2 (OBL = "OBL"): <double>.
ℹ Input `value_median` is `median(OCCLEN_FP, na.rm = TRUE)`.

**Comment by ewenharrison** [comment]
The dependent variable in `summary_factorlist()` should be in inverted commas, unless you have defined it separately?

Otherwise, finalfit has its own label function which should be used in preference. 
```
STF3 %>% 
  mutate(OCCLEN_FP = ff_label(OCCLEN_FP, "Occlusion Length") %>% 
  summary_factorlist(obl, vasc, cont = "median", column = T, p=TRUE, total_col = T )
```
Please let me know if that does or doesn't work.

**Comment by adam-mdmph** [comment]
Thanks for the help!
