### ISSUE TITLE
Multivariate or_plot

### ISSUE THREAD

**Issue by gagonzalezm** [ewenharrison/finalfit#67]
Dear Ewen

Thanks for your work.
I have a question about OR_plot.  is it plotting multivariate or univariate analysis?
Is it possible choose one of them?and how?

when I compare con other glm regression OR output, results are not similar

This is my code :

```
## OR plot
explanatory = c("gender", "educ", "age_cat", "weigth_reported", "pastry_dicho ", "frit_dicho","fast_dicho",
                "sweet_bev_dicho", "fruts_dicho ", "veget_dicho ","bai_cat", "sh_cat" )

dependent = "inc.size"

dat %>%
  or_plot(dependent, explanatory,
          table_text_size=4, title_text_size=14,
          dependent_label = "Outcome Variable: Increased serving size",
          suffix = " ",
          plot_opts=list(xlab("OR, 95% CI"),
                         theme(axis.title = element_text(size=12)
                         )
          )
  )

##glm model

mod_size <- glm(inc.size ~ gender + educ + age_cat + weigth_reported + pastry_dicho +
                  frit_dicho + fast_dicho  +
                  sweet_bev_dicho + fruts_dicho  + veget_dicho +
                  bai_cat + sh_cat,
                dat_model, family = binomial(link='logit'), na.action = NULL)

```

Thank you a lot.

**Comment by ewenharrison** [comment]
Hi,
`or_plot` produces a plot of multivariable data, not univariable. Univariable is not currently supported. 
The results from your two models above should be the same. Your glm model is what `or_plot` does under the hood. 
I'd need a reproducible example if you wanted to explore any difference.
Many thanks.

**Comment by gagonzalezm** [comment]
Thank you Ewen, 
Super hyper fast response!! 
Then, I going  to review again what is happening  and contribute with a reproducible example

Regards
