### ISSUE TITLE
question about confint_type

### ISSUE THREAD

**Issue by acebollada** [ewenharrison/finalfit#71]
Hello
I have a problem running a mixed effects model with finalfit (glmmixed) when calculating the confidence interval. I get the error .

`Error in confint[, 1]`

When I change the **confint_type** parameter to "profile" I get the error 

```
Error in zeta(shiftpar, start = opt[seqpar1][-w]) : 
  profiling detected new, lower deviance 
```

which is related to the lmer function. 
I think I have to change the zeta parameter, is it possible to do it from the finalfit function?

Thank you very much for your help

Alberto Cebollada

**Comment by ewenharrison** [comment]
Hi, sorry, I missed this question. 
Are you able to provide a reproducible example of the error?
Many thanks.
