### ISSUE TITLE
A couple of bugs with missing_plot

### ISSUE THREAD

**Issue by nathansam** [ewenharrison/finalfit#72]
Hi there, 

I just thought I would flag a few bugs I have come across whilst using the `missing_plot` function. The `vlabels` variable is created here in a conditional statement and is used later when creating the ggplot object. Therefore if the function is called with `use_labels = FALSE`, the function will error.  

https://github.com/ewenharrison/finalfit/blob/b1fa0f0c155f447a847ac38f994d8b55eec5ffa5/R/missing_plot.R#L39-L42

Having 

```r 
else {
 vlabels = NULL
}
```

fixes the problem. Secondly, the code here:

https://github.com/ewenharrison/finalfit/blob/b1fa0f0c155f447a847ac38f994d8b55eec5ffa5/R/missing_plot.R#L51

only works if the row names are the row numbers. If you use the function in a context where the row names aren't the row numbers (such as after subsetting the data frame), then the plot is bugged (as shown in the screenshot below).

 Replacing the above line with the below line should stop this behaviour. 

```{R}
 df.in$.id = seq(1, nrow(df))
```

I would be happy to open a PR, if you would like the bugs fixed, but it might just be easier for you to make the changes yourselves. 

Kind regards

**Comment by nathansam** [comment]
![Rplot](https://user-images.githubusercontent.com/10416927/125466745-f09ec5e9-853e-40c9-9e70-cfc1c2760fe3.png)

**Comment by ewenharrison** [comment]
Sorry I missed this. Many thanks for posting. 
It is fixed in 1.04.

**Comment by ewenharrison** [comment]
(I should say that this function also fails if there are too many rows in the dataset. It may be a ggplot issue.)
