### ISSUE TITLE
Error: Tibble columns must have compatible sizes.

### ISSUE THREAD

**Issue by AugustWu1996** [ewenharrison/finalfit#73]
Hello, I found an error and couldn't find out why. But I reproduce this error with simple data.

# artificial data
> dat <- tibble(a = 1:100, b = 1:100, c = factor(rep(c("a", "b"), 50)))

# no problem with single variable
> dat %>% finalfit("c", c("a"))

Waiting for profiling to be done...
Waiting for profiling to be done...
 Dependent: c                     a           b          OR (univariable)        OR (multivariable)
            a Mean (SD) 50.0 (29.2) 51.0 (29.2) 1.00 (0.99-1.02, p=0.862) 1.00 (0.99-1.02, p=0.862)

> dat %>% finalfit("c", c("b"))

Waiting for profiling to be done...
Waiting for profiling to be done...
 Dependent: c                     a           b          OR (univariable)        OR (multivariable)
            b Mean (SD) 50.0 (29.2) 51.0 (29.2) 1.00 (0.99-1.02, p=0.862) 1.00 (0.99-1.02, p=0.862)

# error with two variables
> dat %>% finalfit("c", c("a", "b"))

Waiting for profiling to be done...
Waiting for profiling to be done...
Waiting for profiling to be done...
Error: Tibble columns must have compatible sizes. * Size 3: Existing data. * Size 2: Column at position 5. i Only values of size one are recycled.

## error message
Run `rlang::last_error()` to see where the error occurred.
15.stop(fallback)
14.signal_abort(cnd)
13.cnd_signal(error_incompatible_size(n, name, size, "Existing data"))
12.vectbl_recycle_rows(res, first_size, j, given_col_names[[j]])
11.tibble_quos(xs[!is.null], .rows, .name_repair)
10.dplyr::tibble(explanatory, estimate, confint[, 1], confint[, 2], p)
9.extract_fit.glm(.data = .data, explanatory_name = explanatory_name, estimate_name = estimate_name, estimate_suffix = estimate_suffix, exp = exp, confint_type = confint_type, confint_level = confint_level, p_name = p_name)
8.extract_fit(.data = .data, explanatory_name = explanatory_name, estimate_name = estimate_name, estimate_suffix = estimate_suffix, exp = exp, confint_type = confint_type, confint_level = confint_level, p_name = p_name)
7.fit2df.glm(.data = structure(list(coefficients = c(`(Intercept)` = -0.0606169724200038, a = 0.00120033608752483, b = NA), residuals = c(`1` = -1.9423140850751, `2` = 2.05994423711503, `3` = -1.94457898983846, `4` = 2.05740271038476, `5` = -1.94684933842747, `6` = 2.05486727770914, `7` = -1.94912514392666, ...
6.(function (...) { UseMethod("fit2df") })(.data = structure(list(coefficients = c(`(Intercept)` = -0.0606169724200038, ...
5.do.call(fit2df, c(list(.data = glmmulti.out, metrics = metrics, estimate_suffix = " (multivariable)"), args))
4.(function (.data, dependent, explanatory, explanatory_multi = NULL, random_effect = NULL, column = FALSE, keep_models = FALSE, metrics = FALSE, add_dependent_label = TRUE, dependent_label_prefix = "Dependent: ", dependent_label_suffix = "", keep_fit_id = FALSE, ...) ...
3.do.call(finalfit.glm, args)
2.finalfit(., "c", c("a", "b"))
1.dat %>% finalfit("c", c("a", "b"))

**Comment by ewenharrison** [comment]
Many thanks for commenting. Sorry I didn't get a notification about this. 

You are trying to do a binary logistic regression with two independent variables (explanatory) that are identical. This is not possible. 

```
> glm(c ~ a + b, family = binomial, data = dat) %>% 
+   summary()

Call:
glm(formula = c ~ a + b, family = binomial, data = dat)

Deviance Residuals: 
   Min      1Q  Median      3Q     Max  
-1.202  -1.177   0.000   1.177   1.202  

Coefficients: (1 not defined because of singularities)
            Estimate Std. Error z value Pr(>|z|)
(Intercept) -0.06062    0.40312  -0.150    0.880
a            0.00120    0.00693   0.173    0.862
b                 NA         NA      NA       NA

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 138.63  on 99  degrees of freedom
Residual deviance: 138.60  on 98  degrees of freedom
AIC: 142.6

Number of Fisher Scoring iterations: 3
```

It works as expected with a correctly specified model. 

e.g.
```
> dat <- tibble(a = 1:100, b = sample(1:100, 100), c = factor(rep(c("a", "b"), 50)))
> dat %>% finalfit("c", c("a", "b"))
Waiting for profiling to be done...
Waiting for profiling to be done...
Waiting for profiling to be done...
 Dependent: c                     a           b          OR (univariable)        OR (multivariable)
            a Mean (SD) 50.0 (29.2) 51.0 (29.2) 1.00 (0.99-1.02, p=0.862) 1.00 (0.99-1.01, p=0.982)
            b Mean (SD) 54.3 (29.6) 46.7 (28.2) 0.99 (0.98-1.00, p=0.193) 0.99 (0.98-1.00, p=0.196)
```
