### ISSUE TITLE
level percentages of finalfit.coxph

### ISSUE THREAD

**Issue by corneliushennch** [ewenharrison/finalfit#74]
Dear authors of `finalfit`,

before getting to my issue, I'd like to express a big thank you for creating this awesome package. I am using it extensively for a variety of analyses as it seamlessly integrates in my workflow that is heavily based on the tidyverse. 
One thing that bothers me a little when reporting survival models is the fact that the percentages of the variable levels in the "all" column of the `finalfit.coxph` output are wrong as it's always (100.0). It would be awesome if you could implement the correct percentages for the factor levels in a future update.

``` r
library(finalfit)

explanatory = c("age.factor", "sex.factor", "obstruct.factor", "perfor.factor")
dependent = "Surv(time, status)"

colon_s %>%
  finalfit(dependent, explanatory)
#>  Dependent: Surv(time, status)                     all
#>                            Age   <40 years  70 **(100.0)**
#>                                40-59 years 344 **(100.0)**
#>                                  60+ years 515 **(100.0)**
#>                            Sex      Female 445 **(100.0)**
#>                                       Male 484 **(100.0)**
#>                    Obstruction          No 732 **(100.0)**
#>                                        Yes 176 **(100.0)**
#>                    Perforation          No 902 **(100.0)**
#>                                        Yes  27 **(100.0)**
#>           HR (univariable)        HR (multivariable)
#>                          -                         -
#>  0.76 (0.53-1.09, p=0.132) 0.79 (0.55-1.13, p=0.196)
#>  0.93 (0.66-1.31, p=0.668) 0.98 (0.69-1.40, p=0.926)
#>                          -                         -
#>  1.01 (0.84-1.22, p=0.888) 1.02 (0.85-1.23, p=0.812)
#>                          -                         -
#>  1.29 (1.03-1.62, p=0.028) 1.30 (1.03-1.64, p=0.026)
#>                          -                         -
#>  1.17 (0.70-1.95, p=0.556) 1.08 (0.64-1.81, p=0.785)
```

<sup>Created on 2021-09-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Keep up the great work!

**Comment by ewenharrison** [comment]
Many thanks for this. I don't know why I don't get GitHub email notifications for this repo now, very frustrating. Apologies. 

It's not an error, but rather the default for all regression outputs is row proportions. But for survival models, a single "all" column is produced - compare with a binary outcome.

If you wish column proportions, just add `column = TRUE`.

**Comment by corneliushennch** [comment]
I see, I must have overlooked this option in the documentation! Thanks for pointing it out to me and don't worry about the long delay 👍🏼 .

**Comment by ewenharrison** [comment]
Great, thanks. Ewen
