### ISSUE TITLE
Coefficient plot is not plotting the geom_points

### ISSUE THREAD

**Issue by ardarbyshire** [ewenharrison/finalfit#75]
Hi, 

I'm doing a coefficient_plot using final fit but it is only plotting the confidence intervals and not plotting the geom_point for the beta coefficients. Any ideas how to fix this problem.  The same data runs fine for linear regression with final fit. Plot attached. 

Many thanks 
Alex
![Figure 3](https://user-images.githubusercontent.com/88445043/145566537-5322fc6f-88e3-4dd7-88ed-2553c7dc5d7e.jpeg)

**Comment by ardarbyshire** [comment]
Thanks for getting back. I updated my packages and for some reason that seemed to fix the problem! Not quite sure why it worked as code was unchanged. Thanks Alex

**Comment by ewenharrison** [comment]
Great, thanks for letting me know.
