### ISSUE TITLE
blurring in `missing_plot` on bookdown PDF generation

### ISSUE THREAD

**Issue by ishigoya** [ewenharrison/finalfit#76]
I'm using `missing_plot()` in an Rmarkdown file within Rstudio. When I run `missing_plot()` from a code chunk within Rstudio, the plot appears as expected, but when I knit to PDF, there is some blurring or distortion:

![image](https://user-images.githubusercontent.com/16798645/148696249-87602464-584a-4a90-81e4-7cc4e749b006.png)

### Setup

yaml frontmatter:

```
---
title: "..."
output: 
  bookdown::pdf_document2: default
toc: false
---
```

I generated the plot as below from within a code chunk in Rstudio:

```
df %>% missing_plot(explanatory=c("a", "b", "c", ..., "j"))
```

### Version info

‘finalfit’ version 1.0.4
‘ggplot2’ version 3.3.5
‘bookdown’ version 0.24
"R version 4.1.2 (2021-11-01)"
Server: Ubuntu 20.04.3 (running from rocker/rstudio:latest Docker container)

**Comment by ishigoya** [comment]
I'm sorry I couldn't post an example the other day, I was in a bit of a hurry. Here's MWE Rmarkdown code with screenshots.

    ---
    output: pdf_document
    ---
    
    ```{r}
    library(finalfit)
    airquality %>% missing_plot(explanatory=c("Ozone", "Solar.R"))
    ```

From Rmarkdown's plots window (as expected):

![20220119_07h00m07s_grim](https://user-images.githubusercontent.com/16798645/150025638-778e6fba-9191-4096-adf9-6b0273854a8d.png)


From rendered PDF (distorted):

![20220119_06h59m54s_grim](https://user-images.githubusercontent.com/16798645/150025648-545c4d94-12fb-47d7-9595-0ab3a0c2add0.png)

**Comment by ishigoya** [comment]
When I downloaded the PDF file and opened it using different software, the problem is resolved. It looks like this is a problem somewhere in Rstudio.

**Comment by ewenharrison** [comment]
Ok, thanks for letting me know and getting back to me.

**Comment by ewenharrison** [comment]
When I run this I don't reproduce the problem, so I guess it may be a local set-up issue. 

![image](https://user-images.githubusercontent.com/3391394/150106362-36715088-ef6d-4157-b91f-79e507711dfd.png)

**Comment by ishigoya** [comment]
Can you confirm that you selected "knit to PDF"? I think that's the interface that comes up when selecting the "knit to HTML" option. I'm also able to knit to HTML without any problem.

**Comment by ewenharrison** [comment]
Sorry, you are right, my mistake. 
On knitting to PDF and viewing via RStudio I see the same blurring issue that you are.
