### ISSUE TITLE
Table 1 for just description of the study population without columns stratified by outcome variable  

### ISSUE THREAD

**Issue by zawkzaw** [ewenharrison/finalfit#77]
Hello Ewen

With "finalfit", can I produce Table 1 for just description of the important characteristics of  the study participants without columns stratified by outcome variable like Live and Dead? 

Thank you 

Ko Ko Zaw

**Comment by riinuots** [comment]
Yes!
Just use dependent = NULL like this:

``` r
library(finalfit)
explanatory = c("age", "age.factor", "sex.factor", "obstruct.factor")
dependent = NULL
colon_s %>%
  summary_factorlist(dependent, explanatory)
#> No dependent variable(s) provided; defaulting to single-level factor
#>        label      levels         all
#>  Age (years)   Mean (SD) 59.8 (11.9)
#>          Age   <40 years    70 (7.5)
#>              40-59 years  344 (37.0)
#>                60+ years  515 (55.4)
#>          Sex      Female  445 (47.9)
#>                     Male  484 (52.1)
#>  Obstruction          No  732 (80.6)
#>                      Yes  176 (19.4)

Created on 2022-08-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)
```

Best wishes,
Riinu

P.S.! We recently did a live demo on finalfit tips and tricks. Recording here: https://github.com/SurgicalInformatics/healthyr_demos

**Comment by zawkzaw** [comment]
Dear Riinu

Thank you   so much for the reply and the valuable code.
I had to use gtsummay for that purpose. Now I can use the finalfit for
almost all typical publication qualaity tables.

May I suggest you'd better include that codes and description  to your
online book "HealthyR" for benefit to the researchers  using R?.

Best wishes

Ko Ko Zaw
