### ISSUE TITLE
Why the box size is different when using  hr_plot to draw the figure, how to adjust it?

### ISSUE THREAD

**Issue by Laplace3210** [ewenharrison/finalfit#81]
melanoma [%>%](https://finalfit.org/reference/pipe.html) 
    [hr_plot](https://finalfit.org/reference/hr_plot.html)(dependent_os, explanatory)

![image](https://user-images.githubusercontent.com/50813700/221418984-7d98b615-b51e-45fa-9c9d-1bf0583780dc.png)

**Comment by ewenharrison** [comment]
Many thanks. 
The box is proportional to the group size. 
You can edit this:
```
melanoma %>%
   hr_plot(dependent_os, explanatory, 
     plot_opts = list(scale_size(range = c(4, 4)))) # etc.
```

**Comment by Laplace3210** [comment]
It works!!!
Thank you very much
