### ISSUE TITLE
Adjust axes for coef plots?

### ISSUE THREAD

**Issue by JDottt** [ewenharrison/finalfit#87]
Hello finalfit, love the package and it's been so useful for my work, just wondering if it's possible (and if so, whereabouts) to alter the axes manually for coefficient plots?  This may be the breaks function but I'm not sure how works in practice.  

Also, for the finalfit output, are the coefficients unstandardised or standardised, and can I get either ?

Thanks so much
JS

**Comment by ewenharrison** [comment]
Many thanks for the kind words. 

How manual axes breaks work is here:   
[https://finalfit.org/articles/all_plots_examples.html#manually-specifiy-x-axis-breaks](https://finalfit.org/articles/all_plots_examples.html#manually-specifiy-x-axis-breaks)

Any ggplot modification can be added as per here (e.g., anything you might add with a `+` ):   
[https://finalfit.org/articles/all_plots_examples.html#add-plot-options](https://finalfit.org/articles/all_plots_examples.html#add-plot-options)

These are shown with odds ratio plots, but the same should be true for coefficient plots .

Please let us know if you encounter any issues. 

Thanks again.
