### ISSUE TITLE
Multinomial Logistic Regression

### ISSUE THREAD

**Issue by jcruzer2012** [ewenharrison/finalfit#88]
Hey, I have posted my question below but to no avail. I am trying to figure which "Group" is being used as the comparison. 

https://stats.stackexchange.com/questions/619321/multinomial-logistic-regression-in-r-using-finalfit

Thanks!

**Comment by jcruzer2012** [comment]
We typically present multinomial result just in a sentence. We have not figured out a good way to format in a table. Before finding finalfit I was working on making something that compiled all my statistical results, not necessarily for presentation. But a more concise table of those results. I would be more than happy to share that code with you.

**Comment by ewenharrison** [comment]
Many thanks again. 
Yes, if you could provide a typical model using publically available data together with the package you use (vgam or whatever), together with your preferred output table format, then we can have a look.

**Comment by jcruzer2012** [comment]
Will do!

Ill send over some stuff in the next few weeks
