### ISSUE TITLE
About modifying the hr_plot function

### ISSUE THREAD

**Issue by acebollada80** [ewenharrison/finalfit#89]
I have been using your R package and have found the hr_plot function to be incredibly useful for my analysis. However, I have encountered a specific requirement for my project and would greatly appreciate your guidance.

In my dataset, I have a variable that represents a factor with levels A, B, C, D, and E. While I need to build the model using all the levels of this factor, I would like to customize the resulting hr_plot to only display levels B and C. Essentially, I am interested in excluding the HR values corresponding to levels A, D, and E from the generated graph.

I have reviewed the documentation and explored the available parameters of the hr_plot function, but I couldn't find a straightforward solution to this particular need. Could you please provide me with some insights or suggestions on how I can achieve this customization? 

Thank you very much for your time and effort in developing this fantastic R package. I look forward to your response and continued support.

**Comment by ewenharrison** [comment]
Hi, yes, good question.  Appearance of rows can be controlled using `summary_factorlist()`. 

Take an example from the documentation. 

```
library(finalfit)

# HR plot
explanatory = c("age.factor", "sex.factor", "obstruct.factor", "perfor.factor")
dependent = "Surv(time, status)"
colon_s %>%
	hr_plot(dependent, explanatory, dependent_label = "Survival")
```

Here is `summary_factorlist()` for that call. 

```
colon_s %>% 
	summary_factorlist(dependent, explanatory)

Dependent variable is a survival object
       label      levels        all
         Age   <40 years   70 (7.5)
             40-59 years 344 (37.0)
               60+ years 515 (55.4)
         Sex      Female 445 (47.9)
                    Male 484 (52.1)
 Obstruction          No 732 (80.6)
                     Yes 176 (19.4)
 Perforation          No 902 (97.1)
                     Yes   27 (2.9)

```

Edit this as desired. 

```
plot_factorlist = colon_s %>%
	summary_factorlist(dependent, explanatory, fit_id = TRUE, total_col = TRUE) %>% 
	filter(levels != "<40 years")

plot_factorlist

Dependent variable is a survival object
       label      levels        all      Total                fit_id index
             40-59 years 344 (37.0) 344 (37.0) age.factor40-59 years     2
               60+ years 515 (55.4) 515 (55.4)   age.factor60+ years     3
         Sex      Female 445 (47.9) 445 (47.9)      sex.factorFemale     4
                    Male 484 (52.1) 484 (52.1)        sex.factorMale     5
 Obstruction          No 732 (80.6) 732 (80.6)     obstruct.factorNo     6
                     Yes 176 (19.4) 176 (19.4)    obstruct.factorYes     7
 Perforation          No 902 (97.1) 902 (97.1)       perfor.factorNo     8
                     Yes   27 (2.9)   27 (2.9)      perfor.factorYes     9

```

Pass to `hr_plot()`:

```
colon_s %>%
	hr_plot(dependent, explanatory, dependent_label = "Survival",
					factorlist = plot_factorlist)
```

Hope that helps. Thanks again.

**Comment by ewenharrison** [comment]
Great, glad it worked.   
Many thanks again.   
Ewen
