### ISSUE TITLE
Error with or_plot

### ISSUE THREAD

**Issue by megberryman** [ewenharrison/finalfit#90]
I am getting this error when I try to run or_plot()

Error in `geom_errorbarh()`:
! Problem while converting geom to grob.
ℹ Error occurred in the 1st layer.
Caused by error:
! (converted from warning) Removed 3 rows containing missing values (`geom_errorbarh()`).
---
Backtrace:
     ▆
  1. ├─RALacto_BF %>% or_plot(dependent, explanatory)
  2. └─finalfit::or_plot(., dependent, explanatory)
  3.   └─gridExtra::grid.arrange(...)
  4.     └─gridExtra::arrangeGrob(...)
  5.       └─base::lapply(grobs[toconv], ggplot2::ggplotGrob)
  6.         └─ggplot2 (local) FUN(X[[i]], ...)
  7.           ├─ggplot2::ggplot_gtable(ggplot_build(x))
  8.           └─ggplot2:::ggplot_gtable.ggplot_built(ggplot_build(x))
  9.             └─ggplot2:::by_layer(...)
 10.               ├─rlang::try_fetch(...)
 11.               │ ├─base::tryCatch(...)
 12.               │ │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 13.               │ │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 14.               │ │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
 15.               │ └─base::withCallingHandlers(...)
 16.               └─ggplot2 (local) f(l = layers[[i]], d = data[[i]])
 17.                 └─l$draw_geom(d, layout)
 18.                   └─ggplot2 (local) draw_geom(..., self = self)
 19.                     └─self$geom$handle_na(data, self$computed_geom_params)
 20.                       └─ggplot2 (local) handle_na(..., self = self)
 21.                         └─ggplot2::remove_missing(...)
 22.                           └─cli::cli_warn(msg)
 23.                             └─rlang::warn(format_warning(message, .envir = .envir), ...)
 24.                               └─base::warning(cnd)

If I run finalfit() instead of or_plot() everything works just fine. 

Any idea what I am doing wrong?

My code is:
dependent = "X"
explanatory = c("A", "B", "C")
df %>% or_plot(dependent, explanatory)

**Comment by ewenharrison** [comment]
Many thanks. 
Does it not just refer to the error bars which don't exist for reference levels?

**Comment by megberryman** [comment]
Thank you for responding so quickly!  I reran the script the next day and had no problems! Such is R sometimes.
