### ISSUE TITLE
`fct_explicit_na()` was deprecated in forcats 1.0.0

### ISSUE THREAD

**Issue by adamaj99pwr** [ewenharrison/finalfit#91]
When I use ff_glimpse() function, following warning appears:

Warning message:
"`fct_explicit_na()` was deprecated in forcats 1.0.0.
ℹ Please use `fct_na_value_to_level()` instead.
ℹ The deprecated feature was likely used in the finalfit package.
  Please report the issue at <https://github.com/ewenharrison/finalfit/issues>."

**Comment by riinuots** [comment]
Thank you! We've now updated all uses of `fct_explicit_na()` to `fct_na_value_to_level()` so the warning will disappear in the next version of finalfit.
