### ISSUE TITLE
`Namespace in Imports field not imported from: ‘tidyselect’`

### ISSUE THREAD

**Issue by barracuda156** [ewenharrison/finalfit#93]
There is a warning during checks, is it expected?
```
Namespace in Imports field not imported from: ‘tidyselect’
  All declared Imports should be used.
```

**Comment by ewenharrison** [comment]
Thanks for pointing out. `tidyselect` is needed for many e.g. `dplyr` functions used in `finalfit`. 
This is just the check complaining that the package is not called directly. 
I'll make it go away. 
Thanks again for highlighting.
