### ISSUE TITLE
The output from the stratified models example does not align with the results of the stratified Cox model.

### ISSUE THREAD

**Issue by ws00289583** [ewenharrison/finalfit#94]
The sample code from the website:
**explanatory= c("age", "sex", "ulcer", "thickness", "strata(year)")
melanoma %>% 
    finalfit(dependent_os, explanatory) %>% 
    mykable()**

and the output would be: 
```
Sex | Female | 126 (61.5) | - | -
       | Male | 79 (38.5) | 1.93 (1.21-3.07, p=0.006)
```

However, if I fit the model using:
**summary(coxph(Surv(time, status_os) ~ sex + strata(year), data = melanoma))**

The output would be:

```
          coef exp(coef) se(coef)     z Pr(>|z|)   
sexMale 0.7787    2.1786   0.2497 3.118  0.00182
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

        exp(coef) exp(-coef) lower .95 upper .95
sexMale     2.179      0.459     1.335     3.554
```
If I remove + strata(year) from **summary(coxph(Surv(time, status_os) ~ sex + strata(year), data = melanoma))**. The results would be the same.

Thank you in advance for your assistance in resolving this issue. Your dedication to maintaining the package is highly appreciated.

**Comment by ewenharrison** [comment]
Many thanks for your interest and kind words. 

The two models you present above are different. 
The first includes age, sex, ulcer, thickness and year as a strata. 
The second includes sex and year as a strata only. 

If you compare the same models, the results are equivalent. See below. 

Many thanks again. 
Ewen

```
library(finalfit)
library(tidyverse)
library(survival)

melanoma = boot::melanoma

melanoma = melanoma %>%
	mutate(
		# Overall survival
		status_os = ifelse(status == 2, 0, 1)
	)

explanatory = c("sex", "strata(year)")
dependent_os = "Surv(time, status_os)"
melanoma %>%
	finalfit(dependent_os, explanatory) 
# 2.18 (1.34-3.55, p=0.002)

summary(coxph(Surv(time, status_os) ~ sex + strata(year), data = melanoma))
# sexMale  2.1786, 0.00182 **
```

**Comment by ws00289583** [comment]
Thank you, Ewen, for your prompt response. Would it be possible to generate a table of models with various univariate + same strata combinations? The way the table is presented suggests that I should interpret it in this manner since it says "univariate".

**Comment by ewenharrison** [comment]
Ah, yes, good point. No, with standard syntax `univariate` does not incorporate the `strata` term. 
You can do that by adding a new set of models using `ff_merge()` like this. 
I've included a full reproducible example using the code from [here](https://finalfit.org/articles/survival.html), but it is not needed for the principle. 
I'd appreciate if you could check it gives the intended output and confirm with me.   

```
library(finalfit)
library(tidyverse)
library(survival)

# For reproducible example
melanoma = boot::melanoma %>%
  mutate(
                                                               # Overall survival
    status_os = ifelse(status == 2, 0, 1),
		
                                                               # Label and recode other variables
    age = ff_label(age, "Age (years)"),                        # ff_label to make table friendly var labels
    thickness = ff_label(thickness, "Tumour thickness (mm)"), 
    sex = factor(sex) %>% 
      fct_recode("Male" = "1", "Female" = "0") %>% 
      ff_label("Sex"),
    ulcer = factor(ulcer) %>% 
      fct_recode("No" = "0",  "Yes" = "1") %>% 
      ff_label("Ulcerated tumour")
  )


# Important bit from here
dependent_os = "Surv(time, status_os)"
explanatory= c("age", "sex", "ulcer", "thickness")               # No strata

melanoma %>%
  finalfit(dependent_os, explanatory, keep_fit_id = TRUE) %>%    # Standard CoxPH without strata
  select(-7) %>%                                                 # Remove multivariable, or keep if prefer
                                                                 # Merge new set of models with each explanatory+strata
  ff_merge(
    explanatory %>% 
      purrr::map_df(~ coxphmulti(melanoma, dependent_os, c(.x, "strata(year)")) %>% 
        fit2df(estimate_suffix = " (univariable with strata)")
  )) %>% 
	
                                                                 # Merge new multivariable model including strata
  ff_merge(coxphmulti(melanoma, dependent_os, c(explanatory, "strata(year)")) %>% 
    fit2df(estimate_suffix = " (multivariable with strata)"), 
      last_merge = TRUE
  )

# Output
  Dependent: Surv(time, status_os)                   all          HR (univariable) HR (univariable with strata)
1                      Age (years) Mean (SD) 52.5 (16.7) 1.03 (1.01-1.05, p<0.001)    1.03 (1.01-1.05, p<0.001)
2                              Sex    Female  126 (61.5)                         -                            -
3                                       Male   79 (38.5) 1.93 (1.21-3.07, p=0.006)    2.18 (1.34-3.55, p=0.002)
5                 Ulcerated tumour        No  115 (56.1)                         -                            -
6                                        Yes   90 (43.9) 3.52 (2.14-5.80, p<0.001)    3.12 (1.83-5.33, p<0.001)
4            Tumour thickness (mm) Mean (SD)   2.9 (3.0) 1.16 (1.10-1.23, p<0.001)    1.15 (1.08-1.22, p<0.001)
  HR (multivariable with strata)
1      1.03 (1.01-1.05, p=0.002)
2                              -
3      1.75 (1.06-2.87, p=0.027)
5                              -
6      2.61 (1.47-4.63, p=0.001)
4      1.08 (1.01-1.16, p=0.027)
```

**Comment by ws00289583** [comment]
> Ah, yes, good point. No, with standard syntax `univariate` does not incorporate the `strata` term. You can do that by adding a new set of models using `ff_merge()` like this. I've included a full reproducible example using the code from [here](https://finalfit.org/articles/survival.html), but it is not needed for the principle. I'd appreciate if you could check it gives the intended output and confirm with me.
> 
> ```
> library(finalfit)
> library(tidyverse)
> library(survival)
> 
> # For reproducible example
> melanoma = boot::melanoma %>%
>   mutate(
>                                                                # Overall survival
>     status_os = ifelse(status == 2, 0, 1),
> 		
>                                                                # Label and recode other variables
>     age = ff_label(age, "Age (years)"),                        # ff_label to make table friendly var labels
>     thickness = ff_label(thickness, "Tumour thickness (mm)"), 
>     sex = factor(sex) %>% 
>       fct_recode("Male" = "1", "Female" = "0") %>% 
>       ff_label("Sex"),
>     ulcer = factor(ulcer) %>% 
>       fct_recode("No" = "0",  "Yes" = "1") %>% 
>       ff_label("Ulcerated tumour")
>   )
> 
> 
> # Important bit from here
> dependent_os = "Surv(time, status_os)"
> explanatory= c("age", "sex", "ulcer", "thickness")               # No strata
> 
> melanoma %>%
>   finalfit(dependent_os, explanatory, keep_fit_id = TRUE) %>%    # Standard CoxPH without strata
>   select(-7) %>%                                                 # Remove multivariable, or keep if prefer
>                                                                  # Merge new set of models with each explanatory+strata
>   ff_merge(
>     explanatory %>% 
>       purrr::map_df(~ coxphmulti(melanoma, dependent_os, c(.x, "strata(year)")) %>% 
>         fit2df(estimate_suffix = " (univariable with strata)")
>   )) %>% 
> 	
>                                                                  # Merge new multivariable model including strata
>   ff_merge(coxphmulti(melanoma, dependent_os, c(explanatory, "strata(year)")) %>% 
>     fit2df(estimate_suffix = " (multivariable with strata)"), 
>       last_merge = TRUE
>   )
> 
> # Output
>   Dependent: Surv(time, status_os)                   all          HR (univariable) HR (univariable with strata)
> 1                      Age (years) Mean (SD) 52.5 (16.7) 1.03 (1.01-1.05, p<0.001)    1.03 (1.01-1.05, p<0.001)
> 2                              Sex    Female  126 (61.5)                         -                            -
> 3                                       Male   79 (38.5) 1.93 (1.21-3.07, p=0.006)    2.18 (1.34-3.55, p=0.002)
> 5                 Ulcerated tumour        No  115 (56.1)                         -                            -
> 6                                        Yes   90 (43.9) 3.52 (2.14-5.80, p<0.001)    3.12 (1.83-5.33, p<0.001)
> 4            Tumour thickness (mm) Mean (SD)   2.9 (3.0) 1.16 (1.10-1.23, p<0.001)    1.15 (1.08-1.22, p<0.001)
>   HR (multivariable with strata)
> 1      1.03 (1.01-1.05, p=0.002)
> 2                              -
> 3      1.75 (1.06-2.87, p=0.027)
> 5                              -
> 6      2.61 (1.47-4.63, p=0.001)
> 4      1.08 (1.01-1.16, p=0.027)
> ```

Thank you so much, Even! These worked perfectly. I hope you have a wonderful day.
