### ISSUE TITLE
Potential bugs finalfit command

### ISSUE THREAD

**Issue by shoaibraees** [ewenharrison/finalfit#96]
Hi, 
Can you please guide me on two ends? The snapshot from the output table using the "Finalfit" command. 
1. How to get rid of this issue of missing estimates of multivariable regression and weird confidence intervals (to the right end of the snap). 
2. How to get rid of this sequence numbering (to the left end of the snap). It gives some numbering in alphabetic order in R. Please note it is an output from the R console (without using R markdown).  Since the qflex tabs do not work with Finalfit command, we need to have tables that do NOT need to be reformatted. We are not using R markdown. 

Thank you for looking into it! 
![image](https://github.com/ewenharrison/finalfit/assets/151813075/022310c5-5720-4faa-b2de-edbb2b129f37)

**Comment by ewenharrison** [comment]
Hi, many thanks. 
There is a problem with your underlying model, which hasn't converged. This is why you have confidence intervals that go from zero to infinity. There are lots of potential reasons for this, including using the same variable twice (colinearity). 

Depending on where you view a dataframe, you will get row names/numbers. These can be removed. For instance, if you are using `knitr` using `row.names = FALSE`, as per here. 
https://finalfit.org/articles/export.html
