### ISSUE TITLE
Finalfit package: Descriptive statistics query for p values and getting Median as statistics 

### ISSUE THREAD

**Issue by shoaibraees** [ewenharrison/finalfit#97]
Hi there, 
Using a snapshot from your examples, we need guidance abou the package. 
1. Is it possible to get "medians" here along with the means? Please share, how you would write the script to get medians. 
2. Is the p values calaculated using Chi Square? Please share any documentation that can be used as a reference in the publication. Currently, we are not able to find the information which staticcal test is used to estimate these p values. 
Many thanks, 

![image](https://github.com/ewenharrison/finalfit/assets/151813075/b3c9f5dc-73ad-4436-ba09-28280915b8f7)

**Comment by ewenharrison** [comment]
Many thanks for this. 

If you look in the help for the function, you can see all the options available and how to change them. 
https://finalfit.org/reference/summary_factorlist.html

1. For instance, `cont = "median"` allows you to achieve what you want. 
2. Again, if you check the help pages all this information is provided. 
e.g., `p_cat   Character. Categorical variable test. One of either "chisq" or "fisher"`.

Many thanks again.
