### ISSUE TITLE
p>0.05, but 95% confidence interval for the odds ratio DOES NOT include 1. How can I check and standardise the methods used to calculate the p-values and confidence intervals?

### ISSUE THREAD

**Issue by Trypanosome** [ewenharrison/finalfit#98]
I have a missing data variable, "Age_Years", and I have run a logistic regression to see which variables, if any, are associated with having missing "Age_Years" values.

I have used the final fit package in R. I have attached the output from the regression in the following link as I was not able to upload the code in a convenient and readable form, even using the ' ' (sorry, this is my first time using GitHub to post or ask questions)

[Age - Missing - Logistic Regression.docx](https://github.com/ewenharrison/finalfit/files/13555723/Age.-.Missing.-.Logistic.Regression.docx)

 My question/curiosity is, why do I have a p-value (in the multivariable column) that is >0.05 when the 95% confidence interval for the odds ratio does NOT include 1? There are numerous examples in the output, including for "Workplace_Cassava", "Treated_bednet_count", "Time_owned_personal_bednet_Years", "Elevated_house", and "Infected_household".

I notice that for most of the "dubious" variables, the 95% confidence interval is very wide, but not for all (Time owned personal bednet, for example). Besides, I would have thought it would not have mattered how wide the confidence interval was; I would have thought (just based on the underlying mathematics of statistics) that if the 95% confidence interval does not include 1, then the p-value should be <0.05, and vice-versa, but that is not the case.

I am assuming that it might be because the methods used to calculate the 95% CIs and the p-values are not the same, but I have no idea how to check this or standardise this.

How can I check the methods and standardise them?

Thanks

**Comment by ewenharrison** [comment]
Many thanks for your question / point - it's important, well spotted. The bottom line is that this is due to different underlying methods which are used by default in r `glm()` to determine p-values and confidence intervals. It also serves to highlight that the arbitrary p = 0.05 cut-off is just that, arbitrary. 

Here's an example to explain. Apologies for the recode of the `melanoma` dataset first - this is where I've seen it happening. 

```
library(finalfit)
library(tidyverse)

# Data
melanoma = boot::melanoma

# Recode
melanoma = melanoma %>% 
  mutate(died_melanoma.factor = case_when(
    status == 1~ "Yes",
    status == 2 ~ "No",
    status == 3 ~ "No") %>% 
      factor()) %>% 
  mutate(stage.factor = cut(thickness, 
           breaks = c(0,0.5,1,4, max(thickness, na.rm = TRUE)), include.lowest = TRUE)) %>% 
  mutate(stage.factor = stage.factor %>% 
           fct_recode("Stage I" = "[0,0.5]",
                      "Stage II" = "(0.5,1]",
                      "Stage III" = "(1,4]",
                      "Stage IV" = "(4,17.4]"))
```

Here is an example model. 

```
# Standard model
dependent="died_melanoma.factor"
explanatory = c("age", "sex", "stage.factor")

melanoma %>% finalfit(dependent, explanatory)
Waiting for profiling to be done...
Waiting for profiling to be done...
Waiting for profiling to be done...
Waiting for profiling to be done...
 Dependent: died_melanoma.factor                    No         Yes             OR (univariable)           OR (multivariable)
                             age Mean (SD) 51.5 (16.1) 55.1 (17.9)    1.01 (0.99-1.03, p=0.163)    1.01 (0.99-1.03, p=0.534)
                             sex         0   98 (77.8)   28 (22.2)                            -                            -
                                         1   50 (63.3)   29 (36.7)    2.03 (1.09-3.79, p=0.025)    1.62 (0.81-3.21, p=0.167)
                    stage.factor   Stage I   18 (94.7)     1 (5.3)                            -                            -
                                  Stage II   32 (86.5)    5 (13.5)   2.81 (0.41-56.12, p=0.362)   2.83 (0.40-56.96, p=0.363)
                                 Stage III   75 (72.1)   29 (27.9)  6.96 (1.34-128.04, p=0.065)  7.17 (1.37-132.38, p=0.061)
                                  Stage IV   23 (51.1)   22 (48.9) 17.22 (3.13-322.85, p=0.008) 14.30 (2.54-270.31, p=0.014)
```

Note the result in the multivariable model for Stage III disease - `7.17 (1.37-132.38, p=0.061)`. A 95% confidence interval that excludes `1`, but a p-value which is great than `0.05`.

By default in R `glm`, confidence intervals are produced using the `profile` method, while the p-value produced uses the `default` Wald approach. Using the Wald approach produces compatible results. 

```
melanoma %>% finalfit(dependent, explanatory, confint_type = "default")
 Dependent: died_melanoma.factor                    No         Yes             OR (univariable)           OR (multivariable)
                             age Mean (SD) 51.5 (16.1) 55.1 (17.9)    1.01 (0.99-1.03, p=0.163)    1.01 (0.99-1.03, p=0.534)
                             sex         0   98 (77.8)   28 (22.2)                            -                            -
                                         1   50 (63.3)   29 (36.7)    2.03 (1.09-3.78, p=0.025)    1.62 (0.82-3.21, p=0.167)
                    stage.factor   Stage I   18 (94.7)     1 (5.3)                            -                            -
                                  Stage II   32 (86.5)    5 (13.5)   2.81 (0.30-25.98, p=0.362)   2.83 (0.30-26.59, p=0.363)
                                 Stage III   75 (72.1)   29 (27.9)   6.96 (0.89-54.54, p=0.065)   7.17 (0.91-56.54, p=0.061)
                                  Stage IV   23 (51.1)   22 (48.9) 17.22 (2.12-140.14, p=0.008) 14.30 (1.73-118.23, p=0.014)
```
This is the same result of default `R` approaches. Using base R. 
```
fit = glm(ff_formula(dependent, explanatory), family = binomial, data = melanoma)

fit %>% 
  summary()

Call:
glm(formula = ff_formula(dependent, explanatory), family = binomial, 
    data = melanoma)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.2961  -0.7925  -0.6285   1.1172   2.4592  

Coefficients:
                       Estimate Std. Error z value Pr(>|z|)   
(Intercept)           -3.393688   1.183975  -2.866  0.00415 **
age                    0.006263   0.010067   0.622  0.53386   
sex                    0.481865   0.348785   1.382  0.16711   
stage.factorStage II   1.039436   1.143481   0.909  0.36334   
stage.factorStage III  1.970525   1.053333   1.871  0.06138 . 
stage.factorStage IV   2.660520   1.077625   2.469  0.01355 * 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 242.35  on 204  degrees of freedom
Residual deviance: 220.28  on 199  degrees of freedom
AIC: 232.28

Number of Fisher Scoring iterations: 5

fit %>% 
  confint() %>% 
  exp()

Waiting for profiling to be done...
                            2.5 %      97.5 %
(Intercept)           0.001580922   0.2459713
age                   0.986782157   1.0267251
sex                   0.813346104   3.2099940
stage.factorStage II  0.403315886  56.9647637
stage.factorStage III 1.369791327 132.3821463
stage.factorStage IV  2.542208231 270.3081309

fit %>% 
  confint.default() %>% 
  exp()

                            2.5 %      97.5 %
(Intercept)           0.003298669   0.3419333
age                   0.986621817   1.0263355
sex                   0.817307116   3.2074314
stage.factorStage II  0.300669176  26.5921865
stage.factorStage III 0.910309724  56.5440778
stage.factorStage IV  1.730506416 118.2293882

```
 
The p-values produced by the Wald method may be inaccurate, and care must be taken in concluding important results from them. If the profile and Wald approaches given contradictory results, it may because the model is unstable - too many variables, collinearity etc. 

This is suggested here with a third finalfit approach - bootstrapping the model and generating confidence intervals and p-values from those results (as you may know, bootstrapping is when the model fitting is repeated multiple times using different samples of the data to estimate the variability in the parameters. 

As can be seen here, the upper confidence limits are very high suggesting great uncertainty in the value of these coefficients (odds ratios). 

```
glmmulti_boot(melanoma, dependent, explanatory, R = 10000) %>% 
  fit2df()

            explanatory                                OR
1                   age         1.01 (0.98-1.03, p=0.535)
2                   sex         1.62 (0.79-3.33, p=0.183)
3  stage.factorStage II  2.83 (0.40-14739521.49, p=0.278)
4 stage.factorStage III  7.17 (1.65-33552993.15, p=0.004)
5  stage.factorStage IV 14.30 (3.13-74198457.11, p<0.001)

```

Hope that all made sense.
